from __future__ import annotations

import os
import re
import sqlite3
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DB_PATH = ROOT / "database.sqlite"

DATABASE_URL = os.environ.get("DATABASE_URL")
USE_POSTGRES = bool(DATABASE_URL)


# ---------------------------------------------------------------------------
# SQLite schema (unchanged from original)
# ---------------------------------------------------------------------------

SQLITE_SCHEMA = """\
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS people (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    canonical_name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    primary_email TEXT,
    primary_phone TEXT,
    normalized_city TEXT,
    skill_category TEXT DEFAULT 'uncategorized',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS person_emails (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    person_id INTEGER NOT NULL REFERENCES people(id),
    email TEXT NOT NULL,
    normalized_email TEXT NOT NULL,
    source TEXT NOT NULL,
    UNIQUE(person_id, normalized_email)
);

CREATE TABLE IF NOT EXISTS person_phones (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    person_id INTEGER NOT NULL REFERENCES people(id),
    phone TEXT NOT NULL,
    normalized_phone TEXT NOT NULL,
    source TEXT NOT NULL,
    UNIQUE(person_id, normalized_phone)
);

CREATE TABLE IF NOT EXISTS person_skills (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    person_id INTEGER NOT NULL REFERENCES people(id),
    skill TEXT NOT NULL,
    source TEXT NOT NULL,
    UNIQUE(person_id, skill)
);

CREATE TABLE IF NOT EXISTS source_records (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    person_id INTEGER REFERENCES people(id),
    source_name TEXT NOT NULL,
    row_number INTEGER NOT NULL,
    raw_json TEXT NOT NULL,
    import_batch_id TEXT NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS data_quality_issues (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_name TEXT NOT NULL,
    row_number INTEGER NOT NULL,
    issue_type TEXT NOT NULL,
    original_value TEXT,
    resolved_value TEXT,
    action_taken TEXT NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS match_candidates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    left_person_id INTEGER NOT NULL REFERENCES people(id),
    right_person_id INTEGER NOT NULL REFERENCES people(id),
    reason TEXT NOT NULL,
    confidence TEXT NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(left_person_id, right_person_id, reason)
);

CREATE TABLE IF NOT EXISTS audio_submissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    person_id INTEGER REFERENCES people(id),
    submitter_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    audio_path TEXT NOT NULL,
    audio_data BLOB,
    content_type TEXT,
    duration_seconds REAL,
    sample_rate_khz REAL,
    bitrate_kbps REAL,
    loudness_db REAL,
    quality_estimate TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
"""

# Keep the original SCHEMA name as an alias so any external code referencing
# database.SCHEMA still works.
SCHEMA = SQLITE_SCHEMA


# ---------------------------------------------------------------------------
# PostgreSQL schema
# ---------------------------------------------------------------------------

PG_SCHEMA = """\
CREATE TABLE IF NOT EXISTS people (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    primary_email TEXT,
    primary_phone TEXT,
    normalized_city TEXT,
    skill_category TEXT DEFAULT 'uncategorized',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS person_emails (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INTEGER NOT NULL REFERENCES people(id),
    email TEXT NOT NULL,
    normalized_email TEXT NOT NULL,
    source TEXT NOT NULL,
    UNIQUE(person_id, normalized_email)
);

CREATE TABLE IF NOT EXISTS person_phones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INTEGER NOT NULL REFERENCES people(id),
    phone TEXT NOT NULL,
    normalized_phone TEXT NOT NULL,
    source TEXT NOT NULL,
    UNIQUE(person_id, normalized_phone)
);

CREATE TABLE IF NOT EXISTS person_skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INTEGER NOT NULL REFERENCES people(id),
    skill TEXT NOT NULL,
    source TEXT NOT NULL,
    UNIQUE(person_id, skill)
);

CREATE TABLE IF NOT EXISTS source_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INTEGER REFERENCES people(id),
    source_name TEXT NOT NULL,
    row_number INTEGER NOT NULL,
    raw_json TEXT NOT NULL,
    import_batch_id TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS data_quality_issues (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name TEXT NOT NULL,
    row_number INTEGER NOT NULL,
    issue_type TEXT NOT NULL,
    original_value TEXT,
    resolved_value TEXT,
    action_taken TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS match_candidates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    left_person_id INTEGER NOT NULL REFERENCES people(id),
    right_person_id INTEGER NOT NULL REFERENCES people(id),
    reason TEXT NOT NULL,
    confidence TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(left_person_id, right_person_id, reason)
);

CREATE TABLE IF NOT EXISTS audio_submissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INTEGER REFERENCES people(id),
    submitter_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    audio_path TEXT NOT NULL,
    audio_data BYTEA,
    content_type TEXT,
    duration_seconds REAL,
    sample_rate_khz REAL,
    bitrate_kbps REAL,
    loudness_db REAL,
    quality_estimate TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""


# ---------------------------------------------------------------------------
# SQL translation helpers
# ---------------------------------------------------------------------------

# Pattern for INSERT OR IGNORE — we translate the full statement to use
# ON CONFLICT DO NOTHING for PostgreSQL.
_INSERT_OR_IGNORE_RE = re.compile(r"\bINSERT\s+OR\s+IGNORE\b", re.IGNORECASE)


def _translate_sql(sql: str) -> str:
    """Translate SQLite SQL dialect to PostgreSQL where needed.

    Transformations applied:
    1. ``?`` parameter placeholders  →  ``%s``
    2. ``INSERT OR IGNORE INTO ...`` →  ``INSERT INTO ... ON CONFLICT DO NOTHING``
    """
    # 1. Replace ? placeholders with %s.
    #    We must be careful NOT to replace ? inside string literals.
    #    A simple approach: replace all ? that are not inside single-quotes.
    #    Since none of our SQL uses literal question marks in strings, a
    #    straightforward replace is safe for this codebase.
    translated = sql.replace("?", "%s")

    # 2. INSERT OR IGNORE → INSERT ... ON CONFLICT DO NOTHING
    if _INSERT_OR_IGNORE_RE.search(translated):
        translated = _INSERT_OR_IGNORE_RE.sub("INSERT", translated)
        # Append ON CONFLICT DO NOTHING before any trailing whitespace/semicolons
        translated = translated.rstrip().rstrip(";")
        translated += " ON CONFLICT DO NOTHING"

    return translated


# ---------------------------------------------------------------------------
# PostgreSQL connection wrapper
# ---------------------------------------------------------------------------

class _PgCursorProxy:
    """Wraps a psycopg cursor to provide SQLite-compatible .execute() with
    automatic SQL translation and .lastrowid support."""

    def __init__(self, real_cursor):
        self._cursor = real_cursor
        self.lastrowid = None

    def execute(self, sql: str, params=None):
        translated = _translate_sql(sql)
        if params:
            self._cursor.execute(translated, params)
        else:
            self._cursor.execute(translated)
        # Attempt to extract lastrowid from a RETURNING clause or statusmessage
        try:
            if self._cursor.description and translated.strip().upper().startswith("INSERT"):
                row = self._cursor.fetchone()
                if row and "id" in row:
                    self.lastrowid = row["id"]
        except Exception:
            pass
        return self

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    @property
    def rowcount(self):
        return self._cursor.rowcount

    def __iter__(self):
        return iter(self._cursor)


class _PgConnectionWrapper:
    """Wraps a psycopg connection to provide a SQLite-like interface.

    Key compatibility features:
    - conn.execute(sql, params) translates ? → %s and INSERT OR IGNORE
    - Returns _PgCursorProxy objects for cursor operations
    - commit(), rollback(), close() work as expected
    - Works as a context manager
    - Provides a total_changes attribute (approximation)
    """

    def __init__(self, pg_conn):
        self._conn = pg_conn
        self.total_changes = 0

    def execute(self, sql: str, params=None):
        translated = _translate_sql(sql)
        cursor = self._conn.execute(translated, params)
        if cursor.rowcount and cursor.rowcount > 0:
            self.total_changes += cursor.rowcount
        return _PgCursorProxy._from_raw_cursor(cursor)

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type is None:
            self._conn.commit()
        else:
            self._conn.rollback()
        self._conn.close()
        return False


class _RawPgCursorProxy:
    """Lightweight proxy returned by _PgConnectionWrapper.execute().
    Wraps the raw psycopg cursor returned by Connection.execute()."""

    def __init__(self, raw_cursor):
        self._cursor = raw_cursor
        self.lastrowid = None
        # Try to get rowcount
        try:
            self._rowcount = raw_cursor.rowcount if raw_cursor.rowcount else 0
        except Exception:
            self._rowcount = 0

    def fetchone(self):
        try:
            return self._cursor.fetchone()
        except Exception:
            return None

    def fetchall(self):
        try:
            return self._cursor.fetchall()
        except Exception:
            return []

    @property
    def rowcount(self):
        return self._rowcount

    def __iter__(self):
        return iter(self._cursor)


# Patch _PgCursorProxy to use _RawPgCursorProxy from execute
_PgCursorProxy._from_raw_cursor = staticmethod(lambda c: _RawPgCursorProxy(c))

# Re-implement _PgConnectionWrapper.execute to return _RawPgCursorProxy
def _pg_conn_execute(self, sql, params=None):
    translated = _translate_sql(sql)
    try:
        if params:
            raw_cursor = self._conn.execute(translated, params)
        else:
            raw_cursor = self._conn.execute(translated)
    except Exception:
        raise
    proxy = _RawPgCursorProxy(raw_cursor)
    if proxy._rowcount > 0:
        self.total_changes += proxy._rowcount
    return proxy

_PgConnectionWrapper.execute = _pg_conn_execute


# ---------------------------------------------------------------------------
# Public API: connect(), init_db()
# ---------------------------------------------------------------------------

def connect(path: Path = DB_PATH):
    """Return a database connection.

    When DATABASE_URL is set (Render / PostgreSQL), *path* is ignored and a
    PostgreSQL connection wrapped in _PgConnectionWrapper is returned.

    Otherwise, a standard sqlite3.Connection is returned exactly as before.
    """
    if USE_POSTGRES:
        try:
            import psycopg
            from psycopg.rows import dict_row
        except Exception as exc:
            raise ImportError(
                "psycopg is required for PostgreSQL support. Install psycopg[binary]"
            ) from exc

        # Create a psycopg connection with dictionary-like row factory so existing
        # code can continue to use row["col"] access.
        pg_conn = psycopg.connect(DATABASE_URL, row_factory=dict_row)

        # Wrap the raw connection to present a sqlite-compatible subset used by
        # the rest of the codebase (execute, commit, rollback, close, total_changes,
        # context manager semantics).
        class _PgCursorProxy:
            def __init__(self, raw_cursor):
                self._cursor = raw_cursor
                # Maintain lastrowid for compatibility; psycopg will usually return
                # rows when RETURNING is used, so callers should use fetchone().
                self.lastrowid = None

            def fetchone(self):
                try:
                    return self._cursor.fetchone()
                except Exception:
                    return None

            def fetchall(self):
                try:
                    return self._cursor.fetchall()
                except Exception:
                    return []

            @property
            def rowcount(self):
                try:
                    return self._cursor.rowcount
                except Exception:
                    return 0

            def __iter__(self):
                return iter(self._cursor)

        class _PgConnectionWrapper:
            def __init__(self, raw_conn):
                self._conn = raw_conn
                self.total_changes = 0

            def execute(self, sql: str, params=None):
                translated = _translate_sql(sql)
                cur = self._conn.cursor()
                if params is not None:
                    cur.execute(translated, params)
                else:
                    cur.execute(translated)
                # Update an approximate total_changes from rowcount when available
                try:
                    rc = cur.rowcount if getattr(cur, "rowcount", None) is not None else 0
                    if rc and rc > 0:
                        self.total_changes += rc
                except Exception:
                    pass
                return _PgCursorProxy(cur)

            def commit(self):
                try:
                    self._conn.commit()
                except Exception:
                    raise

            def rollback(self):
                try:
                    self._conn.rollback()
                except Exception:
                    raise

            def close(self):
                try:
                    self._conn.close()
                except Exception:
                    pass

            def __enter__(self):
                return self

            def __exit__(self, exc_type, exc_val, exc_tb):
                if exc_type is None:
                    try:
                        self._conn.commit()
                    except Exception:
                        pass
                else:
                    try:
                        self._conn.rollback()
                    except Exception:
                        pass
                try:
                    self._conn.close()
                except Exception:
                    pass
                return False

        return _PgConnectionWrapper(pg_conn)

    # SQLite path: unchanged behavior
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def init_db(conn) -> None:
    """Create all tables if they don't exist.

    For SQLite, uses executescript with the original schema.
    For PostgreSQL, executes each CREATE TABLE statement individually.
    """
    if USE_POSTGRES:
        # For PostgreSQL, execute each CREATE statement separately and do NOT send
        # SQLite PRAGMA statements to Postgres.
        for statement in PG_SCHEMA.split(";"):
            statement = statement.strip()
            if statement:
                conn.execute(statement)
        conn.commit()
    else:
        # For SQLite, use executescript as before
        if hasattr(conn, 'executescript'):
            conn.executescript(SQLITE_SCHEMA)
            conn.commit()
        else:
            conn.execute(SQLITE_SCHEMA)
            conn.commit()


def is_postgres() -> bool:
    """Return True if the application is configured to use PostgreSQL."""
    return USE_POSTGRES
